version: '3.8'

services:

  core_service:
    build:
      context: ./apps/core_microservice 
      dockerfile: Dockerfile
    container_name: core_service
    ports:
      - "3001:3000"
    volumes:
      - ./apps/core_microservice:/App
      - /App/node_modules
    
    restart: unless-stopped
    env_file:
      - ./apps/core_microservice/.env
    networks:
      - innogram-network
    depends_on:
      postgres:
        condition: service_healthy
      auth_service:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/docs || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  auth_service:
    build:
      context: ./apps/auth_microservice 
      dockerfile: Dockerfile
    container_name: auth_service
    ports:
      - "3002:3002"
    volumes:
      - ./apps/auth_microservice:/App
      - /App/node_modules
    restart: unless-stopped
    env_file:
      - ./apps/auth_microservice/.env
    networks:
      - innogram-network
    depends_on:
      postgres:
        condition: service_healthy
      redis: 
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  postgres:
    image: postgres:15
    container_name: innogram-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - innogram-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: innogram-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - innogram-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  client_app:
    build:
      context: ./apps/client_app 
      dockerfile: Dockerfile
    container_name: client_app
    ports:
     
      - "3000:80" 
    networks:
      - innogram-network
    depends_on:
      core_service:
        condition: service_started

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: innogram-rabbitmq
  #   environment:
  #     RABBITMQ_DEFAULT_USER: innogram
  #     RABBITMQ_DEFAULT_PASS: innogram_password
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   networks:
  #     - innogram-network

volumes:
  postgres_data:
  redis_data:

networks:
  innogram-network:
    driver: bridge
